In [ ]:
import numpy as np 
list1=[1,3,5]
arr=np.array((list1))
print(arr)

[1 3 5]


In [22]:
import numpy as np
list2=[1,3,5],[2,4,6]
arr=np.array(list2)
print(arr)

[[1 3 5]
 [2 4 6]]


In [23]:
import numpy as np
x=np.array([[1,5,7],[3,4,8]])
y=np.array([[2,6,8],[5,7,9]])

a=x+y
b=y-x
c=x*y
d=y/x

print("Addition:", a)
print("Subtraction:", b)
print("Multiplication:", c)
print("Division:", d)


Addition: [[ 3 11 15]
 [ 8 11 17]]
Subtraction: [[1 1 1]
 [2 3 1]]
Multiplication: [[ 2 30 56]
 [15 28 72]]
Division: [[2.         1.2        1.14285714]
 [1.66666667 1.75       1.125     ]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
sum=np.sum(a)
print("The sum is=",sum)

The sum is= 21


In [26]:
import numpy as np
b=np.array([11,12,13])
mean=np.mean(b)
print("The mean is=",mean)

The mean is= 12.0


In [27]:
import numpy as np
c=np.array([23,45,67])
max=np.max(c)
min=np.min(c)
print("The maximum value is=",max)
print("The minimum value is=",min)

The maximum value is= 67
The minimum value is= 23


In [29]:
import numpy as np
a=np.array([[1,5],[3,4]])
b=np.array([[2,6],[5,7]])
x=a @ b
print(x)

[[27 41]
 [26 46]]
